// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Enrollments.Common.Database;

#nullable disable

namespace Service.Enrollments.Common.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928192320_AddEnrollmentIdempotencyAndConcurrencySafety")]
    partial class AddEnrollmentIdempotencyAndConcurrencySafety
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.Enrollments.Common.Database.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasComment("Optimistic concurrency token, regenerated whenever EnrolledCount changes");

                    b.Property<DateTime>("CourseEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("End date of the course");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to the course");

                    b.Property<DateTime>("CourseStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Start date of the course");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was created");

                    b.Property<int>("EnrolledCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Materialized count of active enrollments, kept in sync with the Enrollments table");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer")
                        .HasComment("Maximum number of students allowed in the class");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Deadline for students to register for the class");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was last updated");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Service.Enrollments.Common.Database.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasComment("Class foreign key");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasComment("Course identifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was created");

                    b.Property<DateTime>("EnrollmentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasComment("Student's first name");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasComment("Student identifier");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasComment("Student's last name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was last updated");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CourseId");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CourseId"), "BTREE");

                    b.HasIndex("StudentId");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StudentId"), "BTREE");

                    b.HasIndex("StudentFirstName", "StudentLastName")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StudentFirstName", "StudentLastName"), "GIN");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Service.Enrollments.Common.Database.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Client-supplied key identifying a single enroll/unenroll attempt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time the operation was processed");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasComment("Which operation this key was recorded for (Enroll or Unenroll)");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("Service.Enrollments.Common.Database.Entities.Enrollment", b =>
                {
                    b.HasOne("Service.Enrollments.Common.Database.Entities.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Enrollments_Classes");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Service.Enrollments.Common.Database.Entities.Class", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
