// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Courses.Common.Database;

#nullable disable

namespace Service.Courses.Common.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929152742_AddXminConcurrencyTokenToClassAndCourse")]
    partial class AddXminConcurrencyTokenToClassAndCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.Courses.Common.Database.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier");

                    b.Property<DateTime>("CourseEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("End date of the course");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to the course");

                    b.Property<DateTime>("CourseStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Start date of the course");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was created");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer")
                        .HasComment("Maximum number of students allowed in the class");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Deadline for students to register for the class");

                    b.Property<int>("TotalStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total number of students currently enrolled in the class");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was last updated");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Service.Courses.Common.Database.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasComment("Description of the course");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("text")
                        .HasComment("Name of the course");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date and time when the class was last updated");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Description")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name", "Description"), "GIN");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Service.Courses.Common.Database.Entities.Class", b =>
                {
                    b.HasOne("Service.Courses.Common.Database.Entities.Course", "Course")
                        .WithMany("CourseClasses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Service.Courses.Common.Database.Entities.Course", b =>
                {
                    b.Navigation("CourseClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
